# Generated by Django 2.1.1 on 2018-11-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of city.', max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of company.', max_length=255)),
                ('size', models.IntegerField(blank=True, help_text='Number of employees.', null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(help_text='City where company is located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.City')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of country.', max_length=50, unique=True)),
                ('abbreviation', models.CharField(blank=True, help_text='Optional internet country code assignment.', max_length=4, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunctionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for functional area, e.g. Technology, Marketing, Product Management, Executive Management.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='General description of this functional area.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Industry name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='General description of this industry.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title by which you refer to the project.', max_length=255)),
                ('project_objective', models.TextField(blank=True, help_text='Optional description of the problem solved or anticipated benefits of the project.', null=True)),
                ('start_year', models.IntegerField(help_text='Year this project started.')),
                ('duration', models.IntegerField(help_text='Length of project in weeks.')),
                ('team_size', models.IntegerField(help_text='Number of people that directly contributed to the project.')),
                ('code_repository', models.URLField(blank=True, help_text='Code repository for project, if publicly available.', null=True)),
                ('project_site', models.URLField(blank=True, help_text='Project site, or portion of company website impacted by project, if publicly available.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company associated with the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_quantified_outcomes', models.TextField(blank=True, help_text='Use quantified outcomes if possible, otherwise, note positive outcomes here.', null=True)),
                ('metric_amount', models.IntegerField(blank=True, help_text='Specify the amount of increase or decrease as a positive or negative integer number.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metric_subject', models.ForeignKey(blank=True, help_text='Specify what increased or decreased.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MetricSubject')),
                ('metric_type', models.ForeignKey(blank=True, help_text='Specify how the outcome was measured.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MetricType')),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, to='experience.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Details regarding your functional role, if different from general description.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('involvement_level', models.ForeignKey(help_text='Your type of time commitment to this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.InvolvementLevel')),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, to='experience.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of role, e.g. Software Engineer, Product Manager, Copy Writer, Customer Service Associate.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='General description of this role.', null=True)),
                ('management', models.BooleanField(help_text='Has oversight of fellow team members.')),
                ('leadership', models.BooleanField(help_text='Has executive leadership.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('functional_area', models.ForeignKey(help_text='Functional area this role is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.FunctionalArea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('degree_of_use', models.ForeignKey(help_text='Degree to which you used this skill.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DegreeOfUse')),
                ('project_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.ProjectRole')),
            ],
        ),
        migrations.CreateModel(
            name='RoleTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('degree_of_use', models.ForeignKey(help_text='Degree to which you used this tool.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DegreeOfUse')),
                ('project_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.ProjectRole')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of skill. E.g. Python, Javascript, SEO, Requirements Analysis.', max_length=100)),
                ('version', models.CharField(blank=True, help_text='Version, if applicable. E.g. Python 3.4.', max_length=25, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of state.', max_length=50, unique=True)),
                ('abbreviation', models.CharField(blank=True, help_text='For United States, two character abbreviation for state.', max_length=2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(help_text='Country where state is located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.Country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of tool. E.g. PyCharm, GIMP, Adobe Premiere Pro, MS Office.', max_length=100)),
                ('version', models.CharField(blank=True, help_text='Version, if applicable. E.g. V19.1.6, or Community versus Professional.', max_length=25, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='roletool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.Tool'),
        ),
        migrations.AddField(
            model_name='roleskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.Skill'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='role',
            field=models.ForeignKey(help_text='Your primary functional role on the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.Role'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='work_relationship',
            field=models.ForeignKey(help_text='Your employment relationship to this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.WorkRelationship'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(help_text='Primary source of revenue.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.Industry'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(help_text='State where city is located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.State'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'city')},
        ),
    ]
