# Generated by Django 2.1.1 on 2018-12-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrole',
            name='involvement_level',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='work_relationship',
        ),
        migrations.RemoveField(
            model_name='roleskill',
            name='degree_of_use',
        ),
        migrations.RemoveField(
            model_name='roleskill',
            name='project_role',
        ),
        migrations.RemoveField(
            model_name='roleskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='roletool',
            name='degree_of_use',
        ),
        migrations.RemoveField(
            model_name='roletool',
            name='project_role',
        ),
        migrations.RemoveField(
            model_name='roletool',
            name='tool',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.URLField(blank=True, help_text='Company website; e.g. https://www.opusario.com', null=True),
        ),
        migrations.DeleteModel(
            name='ProjectRole',
        ),
        migrations.DeleteModel(
            name='RoleSkill',
        ),
        migrations.DeleteModel(
            name='RoleTool',
        ),
    ]
