# Generated by Django 2.1.1 on 2019-01-27 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import talent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeOfUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_used', models.CharField(help_text='Frequency of use, e.g. Daily, Occasionally', max_length=50, unique=True)),
                ('weight', models.IntegerField(help_text='Weight of use for analysis.')),
                ('display_order', models.IntegerField(default=0, help_text='Numeric value for ordering display.')),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='ExternalAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='External account, e.g. Source code, Social media, Blog.', max_length=50, unique=True)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='InvolvementLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involvement', models.CharField(help_text='Involvement in project, e.g. Core team member, Part-time, Subject matter expert.', max_length=50, unique=True)),
                ('weight', models.IntegerField(help_text='Weight of involvement for analysis.')),
            ],
            options={
                'ordering': ('involvement',),
            },
        ),
        migrations.CreateModel(
            name='MetricSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_subject', models.CharField(help_text='Subject of metric value, e.g. Revenue, Expense.', max_length=25, unique=True)),
            ],
            options={
                'ordering': ('metric_subject',),
            },
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(help_text='Type of measurement value, e.g. Monetary, Percentage.', max_length=20, unique=True)),
            ],
            options={
                'ordering': ('metric_type',),
            },
        ),
        migrations.CreateModel(
            name='MyExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Details regarding your functional role, if different from general description.', null=True)),
                ('project_owner', models.BooleanField(default=False, help_text='Controls sharing of project with other team members.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('involvement_level', models.ForeignKey(help_text='Your type of time commitment to this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.InvolvementLevel')),
            ],
        ),
        migrations.CreateModel(
            name='MyExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL for the account.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name.', max_length=20)),
                ('last_name', models.CharField(help_text='Your last name.', max_length=40)),
                ('nick_name', models.CharField(blank=True, help_text='Optionally, your nickname.', max_length=60, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Subscriber relative URL on Opusario.', null=True)),
                ('photo', models.ImageField(blank=True, help_text='A nice photo of yourself; not an avatar. Although optional, you will get better results when you have one.', null=True, upload_to=talent.models.user_directory_path)),
                ('phone_number', models.IntegerField(help_text='Contact phone number.')),
                ('email_address', models.EmailField(help_text='Contact email address.', max_length=254)),
                ('passion', models.TextField(blank=True, help_text='Describe what you are good at; what you are passionate about.', null=True)),
                ('personality', models.TextField(blank=True, help_text='A very brief statement about what makes you, YOU.', null=True)),
                ('goals', models.TextField(blank=True, help_text='A very brief description that describes your ambitions and goals.', null=True)),
                ('looking', models.BooleanField(default=False, help_text='Ready for new opportunities.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(help_text='The city where you are located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.City')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('degree_of_use', models.ForeignKey(help_text='Degree to which you used this skill.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.DegreeOfUse')),
            ],
        ),
        migrations.CreateModel(
            name='MyTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('degree_of_use', models.ForeignKey(help_text='Degree to which you used this tool.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.DegreeOfUse')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title by which you refer to the project.', max_length=255)),
                ('project_objective', models.TextField(blank=True, help_text='Optional description of the problem solved or anticipated benefits of the project.', null=True)),
                ('start_year', models.IntegerField(help_text='Year this project started.')),
                ('duration', models.IntegerField(help_text='Length of project in weeks.')),
                ('team_size', models.IntegerField(help_text='Number of people that directly contributed to the project.')),
                ('code_repository', models.URLField(blank=True, help_text='Code repository for project, if publicly available.', null=True)),
                ('project_site', models.URLField(blank=True, help_text='Project site, or portion of company website impacted by project, if publicly available.', null=True)),
                ('non_quantified_outcomes', models.TextField(blank=True, help_text='Use quantified outcomes if possible, otherwise, note positive outcomes here.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company associated with the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_amount', models.IntegerField(blank=True, help_text='Specify the amount of increase or decrease as a positive or negative integer number.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metric_subject', models.ForeignKey(blank=True, help_text='Specify what increased or decreased.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.MetricSubject')),
                ('metric_type', models.ForeignKey(blank=True, help_text='Specify how the outcome was measured.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.MetricType')),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, to='talent.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of role, e.g. Software Engineer, Product Manager, Copy Writer, Customer Service Associate.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='General description of this role.', null=True)),
                ('management', models.BooleanField(help_text='Has oversight of fellow team members.')),
                ('leadership', models.BooleanField(help_text='Has executive leadership.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('functional_area', models.ForeignKey(help_text='Functional area this role is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.FunctionalArea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of skill. E.g. Python, Javascript, SEO, Requirements Analysis.', max_length=100)),
                ('version', models.CharField(blank=True, help_text='Version, if applicable. E.g. Python 3.4.', max_length=25, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of tool. E.g. PyCharm, GIMP, Adobe Premiere Pro, MS Office.', max_length=100)),
                ('version', models.CharField(blank=True, help_text='Version, if applicable. E.g. V19.1.6, or Community versus Professional.', max_length=25, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Work location, e.g. On site, Mixed (on site and remote), Remote.', max_length=30, unique=True)),
            ],
            options={
                'ordering': ('location',),
            },
        ),
        migrations.CreateModel(
            name='WorkRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(help_text='Relationship with employer, e.g. Employee, Consultant, Freelancer.', max_length=30, unique=True)),
            ],
            options={
                'ordering': ('relationship',),
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(help_text='Work schedule, e.g. Full-time, Part-Time, Shared job.', max_length=20, unique=True)),
            ],
            options={
                'ordering': ('schedule',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='mytool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Tool'),
        ),
        migrations.AddField(
            model_name='myskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Skill'),
        ),
        migrations.AddField(
            model_name='myself',
            name='projects',
            field=models.ManyToManyField(related_name='people', through='talent.MyExperience', to='talent.Project'),
        ),
        migrations.AddField(
            model_name='myself',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myself',
            name='work_location',
            field=models.ForeignKey(help_text='Preferred location to do your work.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.WorkLocation'),
        ),
        migrations.AddField(
            model_name='myself',
            name='work_relationship',
            field=models.ForeignKey(help_text='Preferred relationship with organizations you work for.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.WorkRelationship'),
        ),
        migrations.AddField(
            model_name='myself',
            name='work_schedule',
            field=models.ForeignKey(help_text='Preferred type of work schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.WorkSchedule'),
        ),
        migrations.AddField(
            model_name='myexternalaccount',
            name='myself',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Myself'),
        ),
        migrations.AddField(
            model_name='myexternalaccount',
            name='type',
            field=models.ForeignKey(help_text='Type of external account.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.ExternalAccountType'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='myself',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='talent.Myself'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='talent.Project'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='role',
            field=models.ForeignKey(help_text='Your primary functional role on the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.Role'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='skills',
            field=models.ManyToManyField(help_text='Skills used to complete this project.', to='talent.MySkill'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='tools',
            field=models.ManyToManyField(help_text='Tools used to complete this project.', to='talent.MyTool'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='work_relationship',
            field=models.ForeignKey(help_text='Your employment relationship to this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.WorkRelationship'),
        ),
    ]
