# Generated by Django 2.1.1 on 2018-11-18 20:03

from django.db import migrations, models
import django.db.models.deletion
import subscriber.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL for the account.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name.', max_length=20)),
                ('last_name', models.CharField(help_text='Your last name.', max_length=40)),
                ('nick_name', models.CharField(blank=True, help_text='Optionally, your nickname.', max_length=60, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Subscriber relative URL on Opusario.', null=True)),
                ('photo', models.ImageField(blank=True, help_text='A nice photo of yourself; not an avatar. Although optional, you will get better results when you have one.', null=True, upload_to=subscriber.models.user_directory_path)),
                ('phone_number', models.IntegerField(help_text='Contact phone number.')),
                ('email_address', models.EmailField(help_text='Contact email address.', max_length=254)),
                ('passion', models.TextField(help_text='Describe what you are good at; what you are passionate about.')),
                ('personality', models.TextField(blank=True, help_text='A very brief statement about what makes you, YOU.', null=True)),
                ('goals', models.TextField(blank=True, help_text='A very brief description that describes your ambitions and goals.', null=True)),
                ('looking', models.BooleanField(default=False, help_text='Ready for new opportunities.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(help_text='The city where you are located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.City')),
                ('skills', models.ManyToManyField(help_text='Your skills, regardless degree of expertise.', to='experience.Skill')),
                ('tools', models.ManyToManyField(help_text='Tools you use, regardless degree of expertise.', to='experience.Tool')),
                ('work_location', models.ForeignKey(help_text='Preferred location to do your work.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.WorkLocation')),
                ('work_relationship', models.ForeignKey(help_text='Preferred relationship with organizations you work for.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.WorkRelationship')),
                ('work_schedule', models.ForeignKey(help_text='Preferred type of work schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.WorkSchedule')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='myexternalaccount',
            name='myself',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.Myself'),
        ),
        migrations.AddField(
            model_name='myexternalaccount',
            name='type',
            field=models.ForeignKey(help_text='Type of external account.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ExternalAccountType'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='myself',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.Myself'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.Project'),
        ),
    ]
