# Generated by Django 2.1.1 on 2018-12-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20181222_2003'),
        ('core', '0001_initial'),
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('degree_of_use', models.ForeignKey(help_text='Degree to which you used this skill.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DegreeOfUse')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='MyTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('degree_of_use', models.ForeignKey(help_text='Degree to which you used this tool.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DegreeOfUse')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.Tool')),
            ],
        ),
        migrations.RemoveField(
            model_name='myself',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='myself',
            name='tools',
        ),
        migrations.AddField(
            model_name='myexperience',
            name='description',
            field=models.TextField(blank=True, help_text='Details regarding your functional role, if different from general description.', null=True),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='involvement_level',
            field=models.ForeignKey(help_text='Your type of time commitment to this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.InvolvementLevel'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='role',
            field=models.ForeignKey(help_text='Your primary functional role on the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.Role'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='work_relationship',
            field=models.ForeignKey(help_text='Your employment relationship to this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.WorkRelationship'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='skills',
            field=models.ManyToManyField(help_text='Skills used to complete this project.', to='subscriber.MySkill'),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='tools',
            field=models.ManyToManyField(help_text='Tools used to complete this project.', to='subscriber.MyTool'),
        ),
    ]
