# Generated by Django 2.1.1 on 2018-10-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='at_functional_area',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='at_functional_area',
        ),
    ]
