# Generated by Django 2.1.1 on 2018-09-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['name'], 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(help_text='Industry name', max_length=100, unique=True),
        ),
    ]
