# Generated by Django 2.1.1 on 2018-10-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181020_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name', 'version']},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='at_functional_area',
            new_name='functional_area',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='at_role',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='at_role',
        ),
        migrations.AddField(
            model_name='role',
            name='skills',
            field=models.ManyToManyField(help_text='Skills associated with this role.', to='backend.Skill'),
        ),
        migrations.AddField(
            model_name='role',
            name='tools',
            field=models.ManyToManyField(help_text='Tools associated with this role.', to='backend.Tool'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Name of skill. E.g. Python, Javascript, SEO, Requirements Analysis.', max_length=100, unique=True),
        ),
    ]
