# Generated by Django 2.1.1 on 2018-09-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180928_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalarea',
            name='name',
            field=models.CharField(help_text='Name for functional area, e.g. Technology, Marketing, Product Management, Executive Management.', max_length=100, unique=True),
        ),
    ]
