# Generated by Django 2.1.1 on 2018-10-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180928_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(help_text='State where city is located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.State'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(help_text='Country where state is located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Country'),
        ),
    ]
