# Generated by Django 2.1.1 on 2018-10-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20181020_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Name of skill. E.g. Python, Javascript, SEO, Requirements Analysis.', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(help_text='Name of tool. E.g. PyCharm, GIMP, Adobe Premiere Pro, MS Office.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('name', 'version')},
        ),
    ]
