# Generated by Django 2.1.1 on 2018-10-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181020_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='role',
            name='tools',
        ),
    ]
