# Generated by Django 2.1.1 on 2018-10-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20181028_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myexternalaccount',
            options={'ordering': ['url']},
        ),
        migrations.RenameField(
            model_name='myexperience',
            old_name='at_myself',
            new_name='myself',
        ),
        migrations.RenameField(
            model_name='myexperience',
            old_name='at_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='myexternalaccount',
            old_name='at_myself',
            new_name='myself',
        ),
        migrations.RenameField(
            model_name='myexternalaccount',
            old_name='account_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='myself',
            old_name='at_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='at_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='projectoutcome',
            old_name='at_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectrole',
            old_name='at_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='roleskill',
            old_name='at_project_role',
            new_name='project_role',
        ),
        migrations.RenameField(
            model_name='roleskill',
            old_name='at_skill',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='roletool',
            old_name='at_project_role',
            new_name='project_role',
        ),
        migrations.RenameField(
            model_name='roletool',
            old_name='at_tool',
            new_name='tool',
        ),
        migrations.RemoveField(
            model_name='myexternalaccount',
            name='at_account_type',
        ),
        migrations.RemoveField(
            model_name='myself',
            name='at_state',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='at_role',
        ),
        migrations.AddField(
            model_name='myexternalaccount',
            name='type',
            field=models.CharField(choices=[('source', 'Source code'), ('social', 'Social media'), ('blog', 'Blog')], default='social', help_text='Type of external account.', max_length=20),
        ),
        migrations.AddField(
            model_name='myself',
            name='looking',
            field=models.BooleanField(default=False, help_text='Ready for new opportunities.'),
        ),
        migrations.AddField(
            model_name='myself',
            name='skills',
            field=models.ManyToManyField(help_text='Your skills, regardless degree of expertise.', to='backend.Skill'),
        ),
        migrations.AddField(
            model_name='myself',
            name='slug',
            field=models.SlugField(blank=True, help_text='Subscriber relative URL on Opusario.', null=True),
        ),
        migrations.AddField(
            model_name='myself',
            name='tools',
            field=models.ManyToManyField(help_text='Tools you use, regardless degree of expertise.', to='backend.Tool'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='role',
            field=models.ForeignKey(help_text='Your primary functional role on the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Role'),
        ),
        migrations.DeleteModel(
            name='ExternalAccount',
        ),
    ]
