# Generated by Django 2.1.1 on 2018-11-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeOfUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_used', models.CharField(help_text='Frequency of use, e.g. Daily, Occasionally', max_length=50, unique=True)),
                ('weight', models.IntegerField(help_text='Weight of use for analysis.')),
            ],
            options={
                'ordering': ('degree_used',),
            },
        ),
        migrations.CreateModel(
            name='ExternalAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='External account, e.g. Source code, Social media, Blog.', max_length=50, unique=True)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='InvolvementLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involvement', models.CharField(help_text='Involvement in project, e.g. Core team member, Part-time, Subject matter expert.', max_length=50, unique=True)),
                ('weight', models.IntegerField(help_text='Weight of involvement for analysis.')),
            ],
            options={
                'ordering': ('involvement',),
            },
        ),
        migrations.CreateModel(
            name='MetricSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_subject', models.CharField(help_text='Subject of metric value, e.g. Revenue, Expense.', max_length=25, unique=True)),
            ],
            options={
                'ordering': ('metric_subject',),
            },
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(help_text='Type of measurement value, e.g. Monetary, Percentage.', max_length=20, unique=True)),
            ],
            options={
                'ordering': ('metric_type',),
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Work location, e.g. On site, Mixed (on site and remote), Remote.', max_length=30, unique=True)),
            ],
            options={
                'ordering': ('location',),
            },
        ),
        migrations.CreateModel(
            name='WorkRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(help_text='Relationship with employer, e.g. Employee, Consultant, Freelancer.', max_length=30, unique=True)),
            ],
            options={
                'ordering': ('relationship',),
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(help_text='Work schedule, e.g. Full-time, Part-Time, Shared job.', max_length=20, unique=True)),
            ],
            options={
                'ordering': ('schedule',),
            },
        ),
    ]
